### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by teles** [willianribeiro/skoob-bookshelf#1]
Looking for this repo today I didnt find any explications about it.
I would like to know more about this repo and a README.md file should provide informations I want such as:

* How to install (should have)
* How to run (should have)
* How to dev (should have)
* Dependencies (should have)
* How to test (nice to have)
* How to contribute (nice to have)

Or you may use [this template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) to create your README.md.

**Comment by teles** [comment]
Find some inspiration here: https://github.com/matiassingers/awesome-readme

**Comment by teles** [comment]
Any updates on this topic? :) @willianribeiro

**Comment by willianribeiro** [comment]
Thank You so much for your issue (-;

It makes sense. I'm finishing some minimal changes on the project structure and I'll do it soon.

(I'll keep this issue open for tracking this task)

**Comment by teles** [comment]
Thank you @willianribeiro

**Comment by willianribeiro** [comment]
@teles,
I added a very simple version of readme in https://github.com/willianribeiro/skoob-bookshelf/commit/38b587342faee3324506cfe0457cd4dc445ea2c9. As the project evolves I'll update the content of it :+1: 
(You can see the result at the links bellow).

I think I can close this issue now. If You have any other suggestion, please, let me know! 😊

Thank You! :wave: 

--



English:
https://github.com/willianribeiro/skoob-bookshelf/blob/master/README.en.md

Portuguese:
https://github.com/willianribeiro/skoob-bookshelf/blob/master/README.md

**Comment by teles** [comment]
I liked your readme files in both languages. Closing this issue. Congrats.
